# Generated by Django 5.2.16 on 2026-07-31 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("aggregate_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("dispatch_attempts", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TutoringAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("started", "Started"),
                            ("provider_succeeded", "Provider succeeded"),
                            ("validation_failed", "Validation failed"),
                            ("retryable_failed", "Retryable failure"),
                            ("terminal_failed", "Terminal failure"),
                            ("persisted", "Persisted"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("prompt_checksum", models.CharField(max_length=64)),
                ("response_schema_version", models.CharField(max_length=32)),
                ("framework_name", models.CharField(blank=True, max_length=64)),
                ("framework_version", models.CharField(blank=True, max_length=32)),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("requested_model", models.CharField(blank=True, max_length=100)),
                ("served_model", models.CharField(blank=True, max_length=100)),
                ("provider_request_id", models.CharField(blank=True, max_length=255)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_category", models.CharField(blank=True, max_length=64)),
                ("error_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_id", models.SlugField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("system_instructions", models.TextField()),
                (
                    "response_schema_version",
                    models.CharField(default="1", max_length=32),
                ),
                ("model_policy", models.JSONField(default=dict)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_output_tokens", models.PositiveIntegerField(default=1200)),
                ("checksum", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("public_id", "version"),
                        name="unique_tutoring_prompt_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TutoringSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_answer", models.TextField()),
                ("response_language", models.CharField(default="es", max_length=16)),
                ("idempotency_key", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_submissions",
                        to="courses.exerciseversion",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="tutoring.promptversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutoringResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("validated", "Validated"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("structured_content", models.JSONField()),
                ("rendered_html", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tutoring.tutoringattempt",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response",
                        to="tutoring.tutoringsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tutoringattempt",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="tutoring.tutoringsubmission",
            ),
        ),
        migrations.CreateModel(
            name="TutoringQuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("reserved_count", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="courses.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course", "day"),
                        name="unique_daily_tutoring_usage",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("helpful", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="tutoring.tutoringresponse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("response", "user"),
                        name="one_feedback_per_user_response",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tutoringsubmission",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_user_submission_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="tutoringattempt",
            constraint=models.UniqueConstraint(
                fields=("submission", "number"), name="unique_submission_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="tutoringattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("created", "started", "provider_succeeded"))),
                fields=("submission",),
                name="one_active_tutoring_attempt",
            ),
        ),
    ]
