# Generated by Django 5.2.16 on 2026-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="last_error",
            field=models.TextField(blank=True),
        ),
    ]
