# Generated by Django 5.2.16 on 2026-07-31 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("tutoring", "0002_outboxevent_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.SlugField(max_length=100, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tutoring.promptversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutoringOperationalAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("prompt_activated", "Prompt activated"),
                            ("ambiguous_terminated", "Ambiguous attempt terminated"),
                            (
                                "ambiguous_retry_authorized",
                                "Ambiguous retry authorized",
                            ),
                            (
                                "provider_evidence_attached",
                                "Provider evidence attached",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("actor_identifier", models.CharField(max_length=255)),
                ("note", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tutoring.tutoringattempt",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tutoring.promptversion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tutoring.tutoringsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTutoringQuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("reserved_count", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="courses.course"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "day"),
                        name="unique_daily_course_tutoring_usage",
                    )
                ],
            },
        ),
    ]
