# Generated by Django 5.2.16 on 2026-08-01 04:42

import uuid
from django.db import migrations, models


def mark_existing_dispatched_events(apps, schema_editor):
    apps.get_model("tutoring", "OutboxEvent").objects.filter(dispatched_at__isnull=False).update(
        status="dispatched"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0003_activeprompt_tutoringoperationalaudit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("dispatched", "Dispatched"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(mark_existing_dispatched_events, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tutoringoperationalaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("prompt_draft_created", "Prompt draft created"),
                    ("prompt_published", "Prompt published"),
                    ("prompt_activated", "Prompt activated"),
                    ("ambiguous_terminated", "Ambiguous attempt terminated"),
                    ("ambiguous_retry_authorized", "Ambiguous retry authorized"),
                    ("provider_evidence_attached", "Provider evidence attached"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PromptDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_id", models.SlugField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("system_instructions", models.TextField()),
                (
                    "response_schema_version",
                    models.CharField(default="1", max_length=32),
                ),
                ("model_policy", models.JSONField(default=dict)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_output_tokens", models.PositiveIntegerField(default=1200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("public_id", "version"),
                        name="unique_tutoring_prompt_draft_version",
                    )
                ],
            },
        ),
    ]
