# Generated by Django 5.2.16 on 2026-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="humanhelpticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Baja"),
                    ("normal", "Normal"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="humanhelpticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Abierta"),
                    ("assigned", "Asignada"),
                    ("in_progress", "En curso"),
                    ("waiting_for_student", "Esperando al estudiante"),
                    ("resolved", "Resuelta"),
                    ("cancelled", "Cancelada"),
                ],
                default="open",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="ticketassignment",
            name="status",
            field=models.CharField(
                choices=[("active", "Activa"), ("released", "Liberada")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="visibility",
            field=models.CharField(
                choices=[("participants", "Participantes"), ("internal", "Interna")],
                default="participants",
                max_length=20,
            ),
        ),
    ]
